# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Allow docs in PDF/epub format
formats:
  - pdf
  - epub

# Install our theme. I'm doing this here because I don't really want it
# to live in the requirements.txt for this project, instead using tox to
# build docs locally and this config file to install it on RTD
python:
  install:
    - requirements: docs/requirements.txt
      extra_requirements:
        - Pallets-Sphinx-Themes

