language: python
python:
    - "3.6"
sudo: false
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
install:
    - pip install -U pip
    - pip install -U Flask PyJWT six tox coverage coveralls
script:
    - tox
after_success:
    - coveralls
